### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mrpink76** [anjlab/sublime-text-git-autocommit#4]
Hi!

Love the idea!

I'm using sublime text 3 and as stated in the readme I installed the following packages:
* Git
* GitAutoCommit

Unforturnately it does not work for me. It seems to be missing Git.add...

From the console log:

```
reloading plugin GitAutoCommit.git-autocommit
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "git-autocommit in C:\Users\petwich1\AppData\Roaming\Sublime Text 3\Installed Packages\GitAutoCommit.sublime-package", line 10, in <module>
ImportError: No module named 'Git.add'
```

**Comment by dmitrygusev** [comment]
I can confirm it works with Sublime Text 3 build 3114, so the problem is somewhere else.

Maybe you need to restart Sublime after installing Git plugin...

If you type `git` after `Ctrl+Shift+P` do you see any git commands?

**Comment by mrpink76** [comment]
I'm also using Sublime Text 3 build 3114.

> If you type git after Ctrl+Shift+P do you see any git commands?

Yes I see git commands and they work. 
Tried "Git: Add Current File" and "Git: Add..."

Strange...

**Comment by konto-andrzeja** [comment]
@mrpink76 Try to replace
```
import Git.git
import Git.add
```
with
```
import Git.git_commands
```

For me that fix did the trick.

**Comment by dmitrygusev** [comment]
@konto-andrzeja want to do a PR for this?

**Comment by konto-andrzeja** [comment]
@dmitrygusev Sure, [here it is](https://github.com/anjlab/sublime-text-git-autocommit/pull/5).

**Comment by dmitrygusev** [comment]
@konto-andrzeja thanks!

**Comment by dmitrygusev** [comment]
Version 0.2.1 now available via Package Control

`CMD+Shift+P -> Upgrade/Overwrite All Packages`
