### ISSUE TITLE
output in the console: AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by robinrosenstock** [anjlab/sublime-text-git-autocommit#8]
Plugin is working, but I get the following Traceback in the console:

`
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 488, in <lambda>
    run_callback('on_modified', callback, lambda: callback.on_modified(v))
  File "/home/robin/.config/sublime-text-3/Packages/GitAutoCommit/git-autocommit.py", line 62, in on_modified
    if not is_file_from_autocommit_list(view):
  File "/home/robin/.config/sublime-text-3/Packages/GitAutoCommit/git-autocommit.py", line 23, in is_file_from_autocommit_list
    return is_auto_commit_file_exists(os.path.realpath(os.path.dirname(view.file_name())))
  File "./python3.3/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
`

**Comment by geniusupgrader** [comment]
Looks Like it happens when I only the sublime console with `ctrl+shift+p`

**Comment by nbeversl** [comment]
I also get this error.
